name: "Benchmarking Vs Similar libraries"

on:
  workflow_dispatch

jobs:
  python:
    runs-on: ubuntu-latest
    name: Python Benchmark
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lib Install
        run: |
            python -m pip install --upgrade requests wurlitzer
            python -m pip install -r reqs/requirements.txt
            python -m pip install -r scripts/benchmark/requirements.txt
            make python
      
      - name: Run Benchmark
        run: python scripts/benchmark/benchmark_python.py

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: py_benchmark
          path: doc/JOSS/py.PNG
  cpp:
    runs-on: ubuntu-latest
    name: C/C++/SML Benchmark
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package Install
        run: |
            python -m pip install --upgrade requests
            python -m pip install -r reqs/requirements.txt
            make python
            pip install matplotlib func_timeout wurlitzer
            sudo add-apt-repository ppa:kflarsen/mosml
            sudo apt update
            sudo apt install mosml

      - name: TROLL Install
        run: |
            cd ~
            ls -las
            wget http://hjemmesider.diku.dk/~torbenm/Troll/Troll.zip
            unzip Troll.zip
            patch Main.sml /home/runner/work/GNOLL/GNOLL/scripts/benchmark/troll_noprint.patch
            sudo chmod +x compile.sh
            ./compile.sh
            ls -las
            pwd

      - name: DiceParser Install
        run: |
            cd ~
            git clone https://github.com/EBailey67/DiceParser
            cd DiceParser
            make
            cp diceparser ~/diceparser
            ls -las
            pwd

      - name: Benchmark
        run: |
            python3 scripts/benchmark/benchmark_cmd.py

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: cmd_benchmark
          path: doc/JOSS/C++.PNG


