name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntuTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: python deps
      run: python3 -m pip install -r reqs/requirements.txt
    - name: make test
      run: make test
  
  wslTest:

    runs-on: windows-latest

    steps:
    - uses: Vampire/setup-wsl@v1
    - uses: actions/checkout@v2
    - name: python deps
      shell: wsl-bash
      run: python3 -m pip install -r reqs/requirements.txt
    - name: make test
      shell: wsl-bash
      run: make test
